# Generated by Django 5.1.4 on 2024-12-05 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_growth', models.FloatField(default=0)),
                ('earnings', models.FloatField(default=0)),
                ('referrals', models.IntegerField(default=0)),
                ('pancard_image', models.ImageField(blank=True, null=True, upload_to='pancards/')),
                ('is_retired', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
